# Generated by Django 5.2.8 on 2026-01-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='permissions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
